mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('orders/', include('orders.urls')),
    path('reports/', include('reports.urls')),
]

mysite/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('add_customer', views.addCustomer, name='add-customer'),
    path('add_proposal/<int:pk>', views.addProposal, name='add-proposal'),
    path('add_line_item/<int:pk>', views.addLineItem, name='add-line-item'),
    path('edit-customer/<int:pk>', views.editCustomer, name='edit-customer'),
    path('edit-proposal/<int:pk>', views.editProposal, name='edit-proposal'),
    path('edit-line-item/<int:pk>', views.editLineItem, name='edit-line-item'),
    path('edit-price/<int:pk>', views.editPrice, name='edit-price'),
    path('order-summary/<int:pk>', views.orderSummary, name='order-summary'),
    path('delete/<int:pk>/<int:pk2>', views.lineItemDelete.as_view(), name='delete'),
    path('delete-proposal/<int:pk>/<status>', views.confirm_status, name='confirm-status'),
    path('update_status/<int:pk>/<status>', views.update_status, name='update-status'),
]

mysite/reports/urls.py
from django.urls import path
from .views import manufacturingReport, proposalReport
from . import views

app_name = 'reports'

urlpatterns = [
    path('<int:pk>/manufacturing-report', views.manufacturingReport, name='manufacturing-report'),
    path('<int:pk>/proposal-report', views.proposalReport, name='proposal-report'),
    path('<int:pk>/invoice-report', views.invoiceReport, name='invoice-report'),
]

mysite/orders/models.py
from django.db import models
from datetime import datetime, date
from django.urls import reverse


# FUNCTIONS
# -----------------------------------------------------------
def as_fraction(n):
    number = int(n)
    dec = round(n % 1, 4)

    if (dec == 0):
        return number
    else:
        ratio = dec.as_integer_ratio()
        frac = '{}/{}'.format(ratio[0], ratio[1])
        final = '{} {}'.format(number, frac)

        return final

def none_sum(*args):
    args = [a for a in args if not a is None]
    return sum(args) if args else 0

# TABLES
# -----------------------------------------------------------
class customer(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    address = models.CharField(max_length=255, blank=True)
    city = models.CharField(max_length=255, blank=True)
    zip_code = models.CharField(max_length=5, blank=True)
    home_phone = models.CharField(max_length=25, blank=True)
    mobile_phone = models.CharField(max_length=25, blank=True)
    email = models.EmailField(max_length=254, blank=True)

    def save(self, *args, **kwargs):
        self.first_name = self.first_name.capitalize()
        self.last_name = self.last_name.capitalize()
        self.city = self.city.capitalize()
        return super(customer, self).save(*args, **kwargs)

    def __str__(self):
        return '%s %s' % (self.first_name, self.last_name)

    def get_absolute_url(self):
        return reverse('customer-detail', kwargs={'pk': self.pk})

    class Meta:
        db_table = 'customer'


class agent(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=25, blank=True)

    def __str__(self):
        return '%s %s' % (self.first_name, self.last_name)

    def get_absolute_url(self):
        return reverse('agent-detail', kwargs={'pk': self.pk})

    class Meta:
        db_table = 'agent'


class product(models.Model):
    product_name = models.CharField(max_length=45, unique=True)

    def __str__(self):
        return self.product_name

    def get_absolute_url(self):
        return reverse('product-detail', kwargs={'pk': self.pk})

    class Meta:
        db_table = 'product'


class shutter_type(models.Model):
    shutter_type_name = models.CharField(max_length=100, unique=True)
    product = models.ForeignKey(product, models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.shutter_type_name

    def get_absolute_url(self):
        return reverse('shutter-type-detail', kwargs={'pk': self.pk})

    class Meta:
        db_table = 'shutter_type'


class proposal(models.Model):
    STATUS_CHOICES = [('Pending', 'Pending'), ('Completed', 'Completed'), ('Deleted', 'Deleted')]

    created_date = models.DateTimeField(default=datetime.today)
    installation_date = models.DateField(default=date.today)
    customer = models.ForeignKey(customer, models.SET_NULL, blank=True, null=True)
    agents = models.ManyToManyField(agent)
    measured_by = models.ManyToManyField(agent, related_name='proposal_measured_by')
    notes = models.TextField(blank=True)
    order_subtotal = models.FloatField(default=0)
    order_tax = models.FloatField(default=0)
    order_total = models.FloatField(default=0)
    order_down_payment = models.FloatField(default=0)
    order_balance = models.FloatField(default=0)
    add_tax = models.BooleanField(default=False)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='Pending')

    def get_absolute_url(self):
        return reverse('proposal-detail', kwargs={'pk': self.pk})

    class Meta:
        db_table = 'proposal'


class line_item(models.Model):
    MOUNT_CHOICES = [('Int', 'Interior'), ('Ext', 'Exterior')]
    TRIM_CHOICES = [(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]
    TRIM_STYLE_CHOICES = [('Deco', 'Decorative'), ('Square', 'Square (Smooth)'), ('Round', 'Round (Smooth)'), ('Z', 'Z (Primed)'), ('Other', 'Other')]
    LFRAME_CHOICES = [('LF 3/4', 'LF 3/4'), ('LF 1"', 'LF 1"')]
    FRACTION_CHOICES = [(0, ''), (.125, '1/8'), (.25, '1/4'), (.375, '3/8'), (.5, '1/2'), (.625, '5/8'), (.75, '3/4'), (.875, '7/8')]
    FINISH_CHOICES = [('Paint', 'Paint'), ('Stain', 'Stain')]
    STAIN_CHOICES = [('Ash', 'Ash'), ('Basswood', 'Basswood'), ('Knotty Alder', 'Knotty Alder'), ('Maple', 'Maple'), ('Pine', 'Pine')]
    LOUVER_CHOICES = [(2.5, '2 1/2'), (3.5, '3 1/2'), (4.5, '4 1/2')]
    HINGE_CHOICES = [('LR', 'Left/Right'), ('L', 'Left'), ('R', 'Right')]
    HINGE_COLOR_CHOICES = [('Bronze', 'Bronze'), ('Nickel', 'Nickel'), ('White', 'White'), ('Bright White', 'Bright-White'), ('Off White', 'Off-White'), ('No Hinges', 'No Hinges'), ('Other', 'Other')]
    TILT_ROD_CHOICES = [('Normal', 'Normal'), ('Side and Back', 'Side and Back'), ('Aluminum', 'Aluminum')]
    CUTOUT_CHOICES = [('Mosca', 'Mosca'), ('Luna', 'Luna'), ('Sol', 'Sol')]

    proposal = models.ForeignKey(proposal, models.SET_NULL, blank=True, null=True)
    product = models.ForeignKey(product, models.SET_NULL, blank=True, null=True)
    shutter_type = models.ForeignKey(shutter_type, models.SET_NULL, blank=True, null=True)
    location = models.CharField(max_length=100, blank=True)
    mount = models.CharField(max_length=3, choices=MOUNT_CHOICES, blank=True)
    trim = models.IntegerField(choices=TRIM_CHOICES, default=0)
    trim_style = models.CharField(max_length=10, choices=TRIM_STYLE_CHOICES, blank=True)
    panels = models.IntegerField(blank=True, null=True)
    t_post = models.IntegerField(blank=True, null=True)
    finish = models.CharField(max_length=5, choices=FINISH_CHOICES, blank=True, null=True)
    stain = models.CharField(max_length=15, choices=STAIN_CHOICES, blank=True, null=True)
    color = models.CharField(max_length=100, blank=True)
    louver = models.FloatField(choices=LOUVER_CHOICES, blank=True, null=True)
    hinges = models.CharField(max_length=2, choices=HINGE_CHOICES, blank=True)
    hinge_color = models.CharField(max_length=15, choices=HINGE_COLOR_CHOICES, blank=True)
    tilt_rod = models.CharField(max_length=15, choices=TILT_ROD_CHOICES, blank=True)
    door_handle_cutout = models.CharField(max_length=5, choices=CUTOUT_CHOICES, blank=True)
    resaque_lframe = models.BooleanField(default=False)
    frame_type = models.CharField(max_length=10, choices=LFRAME_CHOICES, blank=True)
    width = models.IntegerField(blank=True, null=True)
    height = models.IntegerField(blank=True, null=True)
    height_left = models.IntegerField(blank=True, null=True)
    height_right = models.IntegerField(blank=True, null=True)
    height_center = models.IntegerField(blank=True, null=True)
    width_fraction = models.FloatField(choices=FRACTION_CHOICES, default=0)
    height_fraction = models.FloatField(choices=FRACTION_CHOICES, default=0)
    height_left_fraction = models.FloatField(choices=FRACTION_CHOICES, default=0)
    height_right_fraction = models.FloatField(choices=FRACTION_CHOICES, default=0)
    height_center_fraction = models.FloatField(choices=FRACTION_CHOICES, default=0)
    height_door_knob = models.IntegerField(blank=True, null=True)
    height_door_knob_fraction = models.FloatField(choices=FRACTION_CHOICES, default=0)
    height_divider = models.IntegerField(blank=True, null=True)
    height_divider_fraction = models.FloatField(choices=FRACTION_CHOICES, default=0)
    height_middle = models.IntegerField(blank=True, null=True)
    height_middle_fraction = models.FloatField(choices=FRACTION_CHOICES, default=0)
    price_per_sq_ft = models.FloatField(blank=True, null=True)


    def modHeight(self):
        # adjust height for:
        # shutter model #7: height center - (width / 2)
        # shutter model #8: height center - width
        # shutter model #12: height center
        h_c = none_sum(self.height_center, self.height_center_fraction)
        w = self.width + self.width_fraction

        if self.shutter_type_id == 7:
            h = h_c - (w / 2)
        elif self.shutter_type_id == 8:
            h = h_c - w
        elif self.shutter_type_id == 12:
            h = h_c
        else:
            h = none_sum(self.height, self.height_fraction)
        return (h)

    # L frame width and height
    # ------------------------------------------------------
    def LframeW(self): # L frame width
        width = self.width + self.width_fraction

        if self.shutter_type_id == 4:
            Lwidth = width
        else:
            Lwidth = width - 0.375 # -3/8
        return round(Lwidth, 4)

    def LframeH(self): # L frame height
        height = self.modHeight()

        if self.shutter_type_id == 4:
            Lheight = height
        else:
            Lheight = (height - 0.25) if height > 0 else 0 # -1/4
        return round(Lheight, 4)

    # L frame height center, left and right
    # ------------------------------------------------------
    def LframeHC(self): # L frame height center
        height = none_sum(self.height_center, self.height_center_fraction)
        Lheight = (height - 0.25) if height > 0 else 0 # -1/4
        return round(Lheight, 4)

    def LframeHL(self): # L frame height left
        height = none_sum(self.height_left, self.height_left_fraction)
        Lheight = (height - 0.25) if height > 0 else 0 # -1/4
        return round(Lheight, 4)

    def LframeHR(self): # L frame height right
        height = none_sum(self.height_right, self.height_right_fraction)
        Lheight = (height - 0.25) if height > 0 else 0 # -1/4
        return round(Lheight, 4)

    # rail, louver, stile, tilt rod
    # ------------------------------------------------------
    def r(self): # rail
        panels = self.panels
        Lwidth = self.LframeW()
        tpost = self.t_post if self.t_post else 0
        frame = self.frame_type

        if tpost > 0:
            if frame == "LF 3/4":
                if panels == 2:

mysite/reports/models.py
from django.db import models

# Create your models here.

mysite/reports/views.py
from django.shortcuts import render
from orders.models import line_item, proposal, customer



def proposalReport(request, pk):
    p = proposal.objects.get(pk=pk)
    p_agents = p.agents.all()
    p_measuredby = p.measured_by.all()
    cust_id = p.customer_id
    cust = customer.objects.get(pk=cust_id)
    lineitem = line_item.objects.filter(proposal_id=pk)

    # calculate proposal total with/without tax
    subtotal = round(sum(i.totalPrice() for i in lineitem), 2)
    tax = round(subtotal*.0825, 2)
    total = subtotal+tax

    return render(request, 'reports/content.html', {'customer': cust, 'proposal': p, 'agents': p_agents, 'measuredby': p_measuredby, 'lineitem': lineitem, 'subtotal': subtotal, 'tax': tax, 'total': total, 'report_name': 'proposal'})


def manufacturingReport(request, pk):
    prop = proposal.objects.get(id=pk)
    p_agents = prop.agents.all()
    p_measuredby = prop.measured_by.all()
    cust_id = prop.customer_id
    cust = customer.objects.get(pk=cust_id)
    lineitem = line_item.objects.filter(proposal_id=pk).order_by('shutter_type_id')

    materials = {
        'totalLframeMaterial': round(sum(i.LframeMaterial() for i in lineitem)),
        'totalLouverMaterial': round(sum(i.louverMaterial() for i in lineitem)),
        'totalRailMaterial': round(sum(i.railMaterial() for i in lineitem)),
        'totalStileMaterial': round(sum(i.stileMaterial() for i in lineitem)),
        'totalTiltRodMaterial': round(sum(i.tiltRodMaterial() for i in lineitem)),
        'totalPanelMaterial': round(sum(i.panelMaterial() for i in lineitem)),
        'totalHinges': round(sum(i.totalHinges() for i in lineitem)),
        'totalMagnets': round(sum(i.magnets() for i in lineitem)),
        'totalScrews': round(sum(i.screws() for i in lineitem))
    }

    return render(request, 'reports/content.html', {'proposal': prop, 'customer': cust, 'agents': p_agents, 'measuredby': p_measuredby, 'lineitem': lineitem, 'materials': materials, 'report_name': 'manufacturing'})



def invoiceReport(request, pk):
    p = proposal.objects.get(pk=pk)
    p_agents = p.agents.all()
    p_measuredby = p.measured_by.all()
    cust_id = p.customer_id
    cust = customer.objects.get(pk=cust_id)
    lineitem = line_item.objects.filter(proposal_id=pk)

    # calculate proposal total with/without tax
    subtotal = round(sum(i.totalPrice() for i in lineitem), 2)
    tax = round(subtotal*.0825, 2)
    total = subtotal+tax

    return render(request, 'reports/content.html', {'customer': cust, 'proposal': p, 'agents': p_agents, 'measuredby': p_measuredby, 'lineitem': lineitem, 'subtotal': subtotal, 'tax': tax, 'total': total, 'report_name': 'invoice'})

mysite/reports/templates/reports/content.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %}New Order{% endblock %}

{% block content %}
<div class="section-wrapper">
  <div class="inner-wrapper">

    {% include "letterhead.html" %}
    <hr/>

    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12 ra">
        {% if report_name == 'proposal' %}
          <h1>Proposal</h1>
        {% elif report_name == 'manufacturing' %}
          <h2>Manufacturing Report</h2>
        {% else %}
          <h1>Invoice</h1>
        {% endif %}
      </div>
    </div>
    <br>

    <div class="row">
      <div class="col-4">
        <h6>PREPARED FOR:</h6>
        {% include "orders/detail_customer.html" %}
      </div>
      <div class="col-4 offset-4">
        <h6>DETAILS:</h6>
        <hr>
        {% include "orders/detail_proposal.html" %}
      </div>
    </div>

    <br>

    {% if report_name == 'proposal' %}
      {% include 'reports/proposal.html' %}
    {% elif report_name == 'manufacturing' %}
      {% include 'reports/manufacturing.html' %}
    {% else %}
      {% include 'reports/invoice.html' %}
    {% endif %}

    <div class="row rf">
      <div class="col-12">
        <button class="btn noprint">
          <a onclick="javascript:print();">Print</a>
        </button> <!-- Print -->
        <button class="btn noprint">
          <a  href="{% url 'orders:order-summary' proposal.id %}">Order Summary</a>
        </button> <!-- HOME -->
      </div>
    </div>
  </div>
</div>


{% endblock %}

mysite/reports/templates/reports/invoice.html
<div class="row">
  <div class = "col-lg-12 col-md-12 col-sm-12">
    <table id="line-item-summary-table">
      <thead>
        <tr>
          <th>#</th>
          <th>Location</th>
          <th>Description</th>
          <th>Total</th>
        </tr>
      </thead>

      <tbody>
      {% for item in lineitem %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>{{ item.location }}</td>
          <td>
            {{ item.product }}, {{ item.shutter_type }} <br><br>
            <b>Finish: </b>{{ item.stain|default_if_none:"" }} {{ item.finish }} - {{ item.color }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <b>Mount: </b>{{ item.mount }} {{ item.trim|default_if_none:"" }} {{ item.get_trim_style_display|default_if_none:"" }}<br>
            <b>Doors: </b>{{ item.panels }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <b>Louver: </b>{{ item.get_louver_display }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <b>Hinge Color:
            </b>{{ item.hinge_color }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <b>Tilt rod: </b>{{ item.tilt_rod }}<br>
          </td>
          <td>$ {{ item.totalPrice }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<div class="row pb">
  <div class="col-lg-8 col-md-8 col-sm-12">
    <div class="report-section">
      <h5>Acceptance of Order: </h5>
      <p>
        The above prices, specifications and conditions are
        satisfactory and are hereby accepted. You are authorized
        to do the work as specified. I am fully aware that there are
        <b>NO CANCELLATIONS</b> and my deposit will not be refunded
        under no circumstances. Payment will be made as outlined
        and agreed upon. By signing below I agree to the terms and
        conditions specified above.
      </p>
    </div>
  </div>
  <div class="col-lg-4 col-md-4 col-sm-12">
    <div class="report-section">
      {% include "orders/detail_price.html" %}
    </div>
  </div>
</div>



<div class="row justify-content-end">
  <div class="col-4">
    <p class="signature textcenter">Customer Signature</p>
  </div>
  <div class="col-2">
    <p class="signature textcenter">Date</p>
  </div>
</div>

mysite/reports/templates/reports/manufacturing.html
{% load widget_tweaks %}
{% load static %}


<br>
{% regroup lineitem by shutter_type_id as lineitem_list %}

{% for i in lineitem_list %}
<div class="section-wrapper no-padding">
  {% for item in i.list %}

    {% if forloop.first %}
      <div class="section-title">
      {{ item.shutter_type }}
    </div> <!-- END section title -->
      <div class="manuf-section-wrapper">
      <div class="row">
      <div class="col-2 no-padding img-col">
        {% with img_id=i.grouper|stringformat:"s" %}
        {% with 'img/model'|add:img_id|add:'.png' as image_static %}
          <img class="shutter-model-img" src="{% static image_static %}" alt="JM Curtain Designer and Blinds L.L.C">
        {% endwith %}
        {% endwith %}
      </div> <!-- END image column -->
    {% endif %}

  {% endfor %}

    <div class="col no-padding">
      <table class="table-theme02">
      {% for item in i.list %}
      {% if forloop.first %}
        <thead>
          <tr>
            <th colspan=2></th>
            <th colspan=2 class="left-border">L Frame</th>

            {% if i.grouper > 5 %}
            <th colspan=3 class="left-border">Height</th>
            {% endif %}

            {% if i.grouper == 4 %}
            <th colspan=2 class="left-border">Door Handle</th>
            <th  class="left-border">Resaque</th>
            {% endif %}

            <th colspan=2 class="left-border">Louver</th>
            <th colspan=2 class="left-border">Rail</th>
            <th colspan=2 class="left-border">Stile</th>
            <th colspan=6 class="left-border"></th>
          </tr>
          <tr>
            <th>#</th>
            <th>Location</th>
            <th class="left-border">Width</th>
            <th>Height</th>

            {% if i.grouper > 5 %}
            <th class="left-border">Center</th>
            <th>Left</th>
            <th>Right</th>
            {% endif %}

            {% if i.grouper == 4 %}
            <th class="left-border">Height</th>
            <th>Cutout</th>
            <th  class="left-border">L Frame</th>
            {% endif %}

            <th class="left-border">Qty</th>
            <th>Medida</th>
            <th class="left-border">Qty</th>
            <th>Medida</th>
            <th class="left-border">Qty</th>
            <th>Medida</th>
            <th class="left-border">Trim</th>
            <th>Trod</th>
            <th>Divider</th>
            <th>Doors</th>
            <th>Hinges</th>
            <th># Tpost</th>
          </tr>
        </thead>
      {% endif %}
        <tbody>
          <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ item.location }}</td>
            <td class="left-border">{{ item.LframeWidth }}</td>
            <td>{{ item.LframeHeight|default_if_none:"" }}</td>

            {% if i.grouper > 5 %}
            <td class="left-border">{{ item.LframeHeightCenter|default_if_none:"" }}</td>
            <td>{{ item.LframeHeightLeft|default_if_none:"" }}</td>
            <td>{{ item.LframeHeightRight|default_if_none:"" }}</td>
            {% endif %}

            {% if i.grouper == 4 %}
            <td class="left-border">{{ item.height_door_knob|default_if_none:"" }} {{ item.height_door_knob_fraction_display|default_if_none:"" }}</td>
            <td>{{ item.door_handle_cutout|default_if_none:"" }}</td>
            <td  class="left-border">{{ item.resaque_lframe|yesno:"Yes," }}</td>
            {% endif %}



            <td class="left-border">{{ item.louverQty }}</td>
            <td>{{ item.louverMeasure }}</td>
            <td class="left-border">{{ item.railQty }}</td>
            <td>{{ item.railMeasure }}</td>
            <td class="left-border">{{ item.stileQty }}</td>
            <td>{{ item.stileMeasure }}</td>
            <td class="left-border">{{ item.trim|default_if_none:"" }}</td>
            <td>{{ item.tiltRodMeasure }}</td>
            <td>{{ item.height_divider|default_if_none:"" }} {{ item.height_divider_fraction_display|default_if_none:"" }}</td>
            <td>{{ item.panels }}</td>
            <td>{{ item.hinges }}</td>
            <td>{{ item.t_post|default_if_none:"" }}</td>
          </tr>
        </tbody>
      {% endfor %}
      </table> <!-- END table -->

      <br>

      {% for item in i.list %}
      {% if forloop.first %}
        <table class="table-theme03 la">
          <thead>
            <tr>
              Order Details:
            </tr>
          </thead>
          <tbody>
            <tr>
              <th>Finish: </th>
              <td>{{ item.stain|default_if_none:"" }} {{ item.finish }} - {{ item.color }}</td>
              <th>Louver: </th>
              <td>{{ item.get_louver_display }}</td>
              <th>Trod: </th>
              <td>{{ item.tilt_rod }}</td>
              <th>Hinge Color: </th>
              <td>{{ item.hinge_color }}</td>
              {% if item.trim_style %}
                <th>Trim: </th>
                <td>{{ item.get_trim_style_display|default_if_none:"" }}</td>
              {% endif %}
              {% if item.frame_type %}
                <th>Frame: </th>
                <td>{{ item.frame_type|default_if_none:"" }}</td>
              {% endif %}
          </tbody>
        </table>
      {% endif %}
      {% endfor %}
    </div> <!-- END column -->
  </div> <!-- END row -->
</div>
</div>
<br>
{% endfor %}


<div class="row">
  <div class="col-9">
    <h6>MATERIALS:</h6>
    <table class="table-theme03 mb">
      <tbody>
        <tr>
          <td>L frame</td>
          <td>Louver</td>
          <td>Rail</td>
          <td>Stile</td>
          <td>Tilt Rod</td>
          <td>Doors</td>
          <td>Hinges</td>
          <td>Magnets</td>
          <td>Screws</td>
        </tr>
        <tr>
          <td>{{ materials.totalLframeMaterial }} ft.</td>
          <td>{{ materials.totalLouverMaterial }} ft.</td>
          <td>{{ materials.totalRailMaterial }} ft.</td>
          <td>{{ materials.totalStileMaterial }} ft.</td>
          <td>{{ materials.totalTiltRodMaterial }} ft.</td>
          <td>{{ materials.totalPanelMaterial }} ft.</td>
          <td>{{ materials.totalHinges }}</td>
          <td>{{ materials.totalMagnets }}</td>
          <td>{{ materials.totalScrews }}</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

mysite/reports/templates/reports/proposal.html
<div class="row">
  <div class = "col-lg-12 col-md-12 col-sm-12">
    <table id="line-item-summary-table">
      <thead>
        <tr>
          <th>#</th>
          <th>Location</th>
          <th>Description</th>
          <th>Total</th>
        </tr>
      </thead>

      <tbody>
      {% for item in lineitem %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>{{ item.location }}</td>
          <td>
            {{ item.product }}, {{ item.shutter_type }} <br><br>
            <b>Finish: </b>{{ item.stain|default_if_none:"" }} {{ item.finish }} - {{ item.color }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <b>Mount: </b>{{ item.mount }} {{ item.trim|default_if_none:"" }} {{ item.get_trim_style_display|default_if_none:"" }}<br>
            <b>Doors: </b>{{ item.panels }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <b>Louver: </b>{{ item.get_louver_display }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <b>Hinge Color:
            </b>{{ item.hinge_color }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <b>Tilt rod: </b>{{ item.tilt_rod }}<br>
          </td>
          <td>$ {{ item.totalPrice }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<div class="row pb">
  <div class="col-lg-8 col-md-8 col-sm-12">
    <div class="report-section">
      <h5>Notes: </h5>
      {{ proposal.notes }}
    </div>
  </div>
  <div class="col-lg-4 col-md-4 col-sm-12">
    <div class="report-section">
      <table id="total-table">
        <tbody>
          <tr>
            <td>Subtotal</td>
            <td class="ra">{{ subtotal }}</td>
          </tr>
          <tr>
            <td>Tax
            </td>
            <td class="ra">{{ tax }}</td>
          </tr>
          <tr class="table-total-row">
            <td><b>TOTAL</b></td>
            <td class="ra">{{ total }}</td>
          </tr>
        </tbody>
      </table> <!-- END total table -->
    </div>
  </div>
</div>