mysite/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.Login, name='login-page'),
    path('home', views.Home, name='home'),
    path('dashboard/<status>', views.updateList, name='update-list'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('orders/', include('orders.urls')),
    path('reports/', include('reports.urls')),
]

mysite/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('add_customer', views.addCustomer, name='add-customer'),
    path('add_proposal/<int:pk>', views.addProposal, name='add-proposal'),
    path('add_line_item/<int:pk>', views.addLineItem, name='add-line-item'),
    path('edit-customer/<int:pk>', views.editCustomer, name='edit-customer'),
    path('edit-proposal/<int:pk>', views.editProposal, name='edit-proposal'),
    path('edit-line-item/<int:pk>', views.editLineItem, name='edit-line-item'),
    path('edit-price/<int:pk>', views.editPrice, name='edit-price'),
    path('order-summary/<int:pk>', views.orderSummary, name='order-summary'),
    path('delete/<int:pk>/<int:pk2>', views.lineItemDelete.as_view(), name='delete'),
    path('delete-proposal/<int:pk>/<status>', views.confirm_status, name='confirm-status'),
    path('update_status/<int:pk>/<status>', views.update_status, name='update-status'),
]

mysite/reports/urls.py
from django.urls import path
from .views import manufacturingReport, proposalReport
from . import views

app_name = 'reports'

urlpatterns = [
    path('<int:pk>/manufacturing-report', views.manufacturingReport, name='manufacturing-report'),
    path('<int:pk>/proposal-report', views.proposalReport, name='proposal-report'),
    path('<int:pk>/invoice-report', views.invoiceReport, name='invoice-report'),
]

mysite/orders/models.py
from django.db import models
from datetime import datetime, date
from django.urls import reverse


# FUNCTIONS
# -----------------------------------------------------------
def as_fraction(n):
    number = int(n)
    dec = round(n % 1, 4)

    if (dec == 0):
        return number
    else:
        ratio = dec.as_integer_ratio()
        frac = '{}/{}'.format(ratio[0], ratio[1])
        final = '{} {}'.format(number, frac)

        return final

def none_sum(*args):
    args = [a for a in args if not a is None]
    return sum(args) if args else 0

# TABLES
# -----------------------------------------------------------
class customer(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    address = models.CharField(max_length=255, blank=True)
    city = models.CharField(max_length=255, blank=True)
    zip_code = models.CharField(max_length=5, blank=True)
    home_phone = models.CharField(max_length=25, blank=True)
    mobile_phone = models.CharField(max_length=25, blank=True)
    email = models.EmailField(max_length=254, blank=True)

    def save(self, *args, **kwargs):
        self.first_name = self.first_name.capitalize()
        self.last_name = self.last_name.capitalize()
        self.city = self.city.capitalize()
        return super(customer, self).save(*args, **kwargs)

    def __str__(self):
        return '%s %s' % (self.first_name, self.last_name)

    def get_absolute_url(self):
        return reverse('customer-detail', kwargs={'pk': self.pk})

    class Meta:
        db_table = 'customer'


class agent(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=25, blank=True)

    def __str__(self):
        return '%s %s' % (self.first_name, self.last_name)

    def get_absolute_url(self):
        return reverse('agent-detail', kwargs={'pk': self.pk})

    class Meta:
        db_table = 'agent'


class product(models.Model):
    product_name = models.CharField(max_length=45, unique=True)

    def __str__(self):
        return self.product_name

    def get_absolute_url(self):
        return reverse('product-detail', kwargs={'pk': self.pk})

    class Meta:
        db_table = 'product'


class shutter_type(models.Model):
    shutter_type_name = models.CharField(max_length=100, unique=True)
    product = models.ForeignKey(product, models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.shutter_type_name

    def get_absolute_url(self):
        return reverse('shutter-type-detail', kwargs={'pk': self.pk})

    class Meta:
        db_table = 'shutter_type'


class proposal(models.Model):
    STATUS_CHOICES = [('Pending', 'Pending'), ('Completed', 'Completed'), ('Deleted', 'Deleted')]

    created_date = models.DateTimeField(default=datetime.today)
    installation_date = models.DateField(default=date.today)
    customer = models.ForeignKey(customer, models.SET_NULL, blank=True, null=True)
    agents = models.ManyToManyField(agent)
    measured_by = models.ManyToManyField(agent, related_name='proposal_measured_by')
    notes = models.TextField(blank=True)
    order_subtotal = models.FloatField(default=0)
    order_tax = models.FloatField(default=0)
    order_total = models.FloatField(default=0)
    order_down_payment = models.FloatField(default=0)
    order_balance = models.FloatField(default=0)
    add_tax = models.BooleanField(default=False)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='Pending')

    def get_absolute_url(self):
        return reverse('proposal-detail', kwargs={'pk': self.pk})

    class Meta:
        db_table = 'proposal'


class line_item(models.Model):
    MOUNT_CHOICES = [('Int', 'Interior'), ('Ext', 'Exterior')]
    TRIM_CHOICES = [(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]
    TRIM_STYLE_CHOICES = [('Deco', 'Decorative'), ('Square', 'Square (Smooth)'), ('Round', 'Round (Smooth)'), ('Z', 'Z (Primed)'), ('Other', 'Other')]
    LFRAME_CHOICES = [('LF 3/4', 'LF 3/4'), ('LF 1"', 'LF 1"')]
    FRACTION_CHOICES = [(0, ''), (.125, '1/8'), (.25, '1/4'), (.375, '3/8'), (.5, '1/2'), (.625, '5/8'), (.75, '3/4'), (.875, '7/8')]
    FINISH_CHOICES = [('Paint', 'Paint'), ('Stain', 'Stain')]
    STAIN_CHOICES = [('Ash', 'Ash'), ('Basswood', 'Basswood'), ('Knotty Alder', 'Knotty Alder'), ('Maple', 'Maple'), ('Pine', 'Pine')]
    LOUVER_CHOICES = [(2.5, '2 1/2'), (3.5, '3 1/2'), (4.5, '4 1/2')]
    HINGE_CHOICES = [('LR', 'Left/Right'), ('L', 'Left'), ('R', 'Right')]
    HINGE_COLOR_CHOICES = [('Bronze', 'Bronze'), ('Nickel', 'Nickel'), ('White', 'White'), ('Bright White', 'Bright-White'), ('Off White', 'Off-White'), ('No Hinges', 'No Hinges'), ('Other', 'Other')]
    TILT_ROD_CHOICES = [('Normal', 'Normal'), ('Side and Back', 'Side and Back'), ('Aluminum', 'Aluminum')]
    CUTOUT_CHOICES = [('Mosca', 'Mosca'), ('Luna', 'Luna'), ('Sol', 'Sol')]

    proposal = models.ForeignKey(proposal, models.SET_NULL, blank=True, null=True)
    product = models.ForeignKey(product, models.SET_NULL, blank=True, null=True)
    shutter_type = models.ForeignKey(shutter_type, models.SET_NULL, blank=True, null=True)
    location = models.CharField(max_length=100, blank=True)
    mount = models.CharField(max_length=3, choices=MOUNT_CHOICES, blank=True)
    trim = models.IntegerField(choices=TRIM_CHOICES, default=0)
    trim_style = models.CharField(max_length=10, choices=TRIM_STYLE_CHOICES, blank=True)
    panels = models.IntegerField(blank=True, null=True)
    t_post = models.IntegerField(blank=True, null=True)
    finish = models.CharField(max_length=5, choices=FINISH_CHOICES, blank=True, null=True)
    stain = models.CharField(max_length=15, choices=STAIN_CHOICES, blank=True, null=True)
    color = models.CharField(max_length=100, blank=True)
    louver = models.FloatField(choices=LOUVER_CHOICES, blank=True, null=True)
    hinges = models.CharField(max_length=2, choices=HINGE_CHOICES, blank=True)
    hinge_color = models.CharField(max_length=15, choices=HINGE_COLOR_CHOICES, blank=True)
    tilt_rod = models.CharField(max_length=15, choices=TILT_ROD_CHOICES, blank=True)
    door_handle_cutout = models.CharField(max_length=5, choices=CUTOUT_CHOICES, blank=True)
    resaque_lframe = models.BooleanField(default=False)
    frame_type = models.CharField(max_length=10, choices=LFRAME_CHOICES, blank=True)
    width = models.IntegerField(blank=True, null=True)
    height = models.IntegerField(blank=True, null=True)
    height_left = models.IntegerField(blank=True, null=True)
    height_right = models.IntegerField(blank=True, null=True)
    height_center = models.IntegerField(blank=True, null=True)
    width_fraction = models.FloatField(choices=FRACTION_CHOICES, default=0)
    height_fraction = models.FloatField(choices=FRACTION_CHOICES, default=0)
    height_left_fraction = models.FloatField(choices=FRACTION_CHOICES, default=0)
    height_right_fraction = models.FloatField(choices=FRACTION_CHOICES, default=0)
    height_center_fraction = models.FloatField(choices=FRACTION_CHOICES, default=0)
    height_door_knob = models.IntegerField(blank=True, null=True)
    height_door_knob_fraction = models.FloatField(choices=FRACTION_CHOICES, default=0)
    height_divider = models.IntegerField(blank=True, null=True)
    height_divider_fraction = models.FloatField(choices=FRACTION_CHOICES, default=0)
    height_middle = models.IntegerField(blank=True, null=True)
    height_middle_fraction = models.FloatField(choices=FRACTION_CHOICES, default=0)
    price_per_sq_ft = models.FloatField(blank=True, null=True)


    def modHeight(self):
        # adjust height for:
        # shutter model #7: height center - (width / 2)
        # shutter model #8: height center - width
        # shutter model #12: height center
        h_c = none_sum(self.height_center, self.height_center_fraction)
        w = self.width + self.width_fraction

        if self.shutter_type_id == 7:
            h = h_c - (w / 2)
        elif self.shutter_type_id == 8:
            h = h_c - w
        elif self.shutter_type_id == 12:
            h = h_c
        else:
            h = none_sum(self.height, self.height_fraction)
        return (h)

    # L frame width and height
    # ------------------------------------------------------
    def LframeW(self): # L frame width
        width = self.width + self.width_fraction

        if self.shutter_type_id == 4:
            Lwidth = width
        else:
            Lwidth = width - 0.375 # -3/8
        return round(Lwidth, 4)

    def LframeH(self): # L frame height
        height = self.modHeight()

        if self.shutter_type_id == 4:
            Lheight = height
        else:
            Lheight = (height - 0.25) if height > 0 else 0 # -1/4
        return round(Lheight, 4)

    # L frame height center, left and right
    # ------------------------------------------------------
    def LframeHC(self): # L frame height center
        height = none_sum(self.height_center, self.height_center_fraction)
        Lheight = (height - 0.25) if height > 0 else 0 # -1/4
        return round(Lheight, 4)

    def LframeHL(self): # L frame height left
        height = none_sum(self.height_left, self.height_left_fraction)
        Lheight = (height - 0.25) if height > 0 else 0 # -1/4
        return round(Lheight, 4)

    def LframeHR(self): # L frame height right
        height = none_sum(self.height_right, self.height_right_fraction)
        Lheight = (height - 0.25) if height > 0 else 0 # -1/4
        return round(Lheight, 4)

    # rail, louver, stile, tilt rod
    # ------------------------------------------------------
    def r(self): # rail
        panels = self.panels
        Lwidth = self.LframeW()
        tpost = self.t_post if self.t_post else 0
        frame = self.frame_type

        if tpost > 0:
            if frame == "LF 3/4":
                if panels == 2:

mysite/orders/views.py
from django.urls import reverse
from django.shortcuts import render, redirect
from .models import customer, proposal, agent, line_item
from .forms import customerForm, proposalForm, lineItemForm
from django.views.generic.edit import DeleteView


# CREATE FORMS ----------------------------------------------------------------
def addCustomer(request):
    f = customerForm()

    if request.method == 'POST':
        form = customerForm(request.POST)

        if form.is_valid():
            form.save()
            p = proposal.objects.create(customer_id=form.instance.id)
            p.save()
            return redirect(reverse('orders:add-line-item', kwargs={'pk': p.id}))

    return render(request, 'orders/content.html', {'form': f, 'form_name': 'customer'})


def addLineItem(request, pk):
    f = lineItemForm(initial={'proposal': pk})
    lineitem = line_item.objects.filter(proposal_id=pk)

    if request.method == 'POST':
        form = lineItemForm(request.POST)

        if form.is_valid():
            li = form.save(commit=False)

            if li.shutter_type_id == 4:
                li.panels = 1
                li.louver = 2.5

            if li.finish == 'Paint':
                li.stain = 'None'

            li.save()

            return redirect(reverse('orders:add-line-item', kwargs={'pk': pk}))

    return render(request, 'orders/content.html', {'form': f, 'lineitem': lineitem, 'proposal_id': pk, 'form_name': 'line_item', 'id': pk})


def addProposal(request, pk):
    p = proposal.objects.get(pk=pk)
    form = proposalForm(request.POST or None, instance=p)
    lineitem = line_item.objects.filter(proposal_id=pk)

    # calculate proposal total with/without tax
    subtotal = round(sum(i.totalPrice() for i in lineitem), 2)

    if form.is_valid():
        new_proposal = form.save(commit=False)
        new_proposal.order_subtotal = subtotal
        new_proposal.order_total = subtotal
        new_proposal.order_balance = subtotal
        new_proposal.save()
        form.save_m2m()
        return redirect(reverse('orders:order-summary', kwargs={'pk': pk}))

    return render(request, 'orders/content.html', {'form': form, 'lineitem': lineitem, 'proposal_id': pk, 'form_name': 'proposal'})


# EDIT FORMS ------------------------------------------------------------------
def editCustomer(request, pk):
    p = proposal.objects.get(customer_id=pk)
    data = customer.objects.get(pk=pk)
    form = customerForm(request.POST or None, instance=data)

    if form.is_valid():
        form.save()
        return redirect(reverse('orders:order-summary', kwargs={'pk': p.id}))

    return render(request, 'orders/content.html', {'form': form, 'form_name': 'customer', 'edit': True, 'id': pk})


def editProposal(request, pk):
    data = proposal.objects.get(pk=pk)
    form = proposalForm(request.POST or None, instance=data)

    if form.is_valid():
        form.save()
        return redirect(reverse('orders:order-summary', kwargs={'pk': pk}))

    return render(request, 'orders/content.html', {'form': form, 'form_name': 'proposal', 'edit': True, 'id': pk})


def editLineItem(request, pk):
    data = line_item.objects.get(pk=pk)
    form = lineItemForm(request.POST or None, instance=data)

    if form.is_valid():
        li = form.save(commit=False)

        if li.shutter_type_id == 4:
            li.panels = 1
            li.louver = 2.5

        if li.finish == 'Paint':
            li.stain = None

        li.save()

        return redirect(reverse('orders:order-summary', kwargs={'pk': data.proposal_id}))

    return render(request, 'orders/content.html', {'form': form, 'form_name': 'line_item', 'edit': True, 'id': data.proposal_id})


def editPrice(request, pk):
    p = proposal.objects.get(pk=pk)
    form = proposalForm(request.POST or None, instance=p)
    lineitem = line_item.objects.filter(proposal_id=pk)

    if form.is_valid():
        new_price = form.save(commit=False)
        if (new_price.add_tax):
            new_price.order_tax = round(new_price.order_subtotal*.0825, 2)
        else:
            new_price.order_tax = 0
        new_price.order_total = round(new_price.order_subtotal + new_price.order_tax,2)
        new_price.order_balance = round(new_price.order_total - new_price.order_down_payment,2)
        new_price.save()
        form.save_m2m()
        return redirect(reverse('orders:order-summary', kwargs={'pk': pk}))

    return render(request, 'orders/content.html', {'proposal': p, 'form': form, 'form_name': 'price', 'edit': True, 'id': pk})

# DELETE FORMS ------------------------------------------------------

# Line Item
class lineItemDelete(DeleteView):
    model = line_item
    template_name = 'orders/confirm_delete.html'

    def get_success_url(self):
        p_id = self.get_object().proposal_id
        return reverse('orders:order-summary', kwargs={'pk': p_id})

# Proposal
def confirm_status(request, pk, status):
    p = proposal.objects.get(pk=pk)

    return render(request, 'orders/confirm_status_update.html', {'p': p, 'status': status})


def update_status(request, pk, status):
    p = proposal.objects.get(pk=pk)

    p.status = status
    p.save()

    return redirect(reverse('dashboard:home'))



# ORDER SUMMARY --------------------------------------------------------------
def orderSummary(request, pk):
    p = proposal.objects.get(pk=pk)
    p_agents = p.agents.all()
    p_measuredby = p.measured_by.all()
    cust_id = p.customer_id
    cust = customer.objects.get(pk=cust_id)
    lineitem = line_item.objects.filter(proposal_id=pk)

    return render(request, 'orders/order_summary.html', {'customer': cust, 'proposal': p, 'agents': p_agents, 'measuredby': p_measuredby, 'lineitem': lineitem, 'report_name': 'order_summary'})

mysite/orders/templates/orders/confirm_delete.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Confirm Delete{% endblock %}

{% block content %}
<div class="row">
  <div class="col-12">
    <p class="summary-title">Order Items</p>
    <hr/>
    <div class="line-item-table-wrapper">
      <table id="line-item-detail-table">
        <thead>
          <tr>
            <th colspan=10></th>
            <th colspan=4>Height</th>
            <th colspan=2>Price</th>
            <th></th>
            <th></th>
          </tr>
          <tr>
            <th>Product</th>
            <th>Type</th>
            <th>Location</th>
            <th>Mount</th>
            <th>Trim</th>
            <th>Trim Style</th>
            <th>Doors</th>
            <th>Hinges</th>
            <th>Width</th>
            <th>Height</th>
            <th>Center</th>
            <th>Left</th>
            <th>Right</th>
            <th>Door Knob</th>
            <th>Per Sq. Ft.</th>
            <th>Total</th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <tr>
            <td>{{ object.product }}</td>
            <td>{{ object.shutter_type }}</td>
            <td>{{ object.location }}</td>
            <td>{{ object.mount }}</td>
            <td>{{ object.trim|default_if_none:"" }}</td>
            <td>{{ object.trim_style|default_if_none:"" }}</td>
            <td>{{ object.panels }}</td>
            <td>{{ object.hinges }}</td>
            <td>{{ object.width }} {{ object.get_width_fraction_display }}</td>
            <td>{{ object.height|default_if_none:"" }} {{ object.get_height_fraction_display }}</td>
            <td>{{ object.height_center|default_if_none:"" }} {{ object.get_height_center_fraction_display }}</td>
            <td>{{ object.height_left|default_if_none:"" }} {{ item.get_height_left_fraction_display }}</td>
            <td>{{ object.height_right|default_if_none:"" }} {{ item.get_height_right_fraction_display }}</td>
            <td>{{ object.height_door_knob|default_if_none:"" }} {{ object.get_height_door_knob_fraction_display }}</td>
            <td>$ {{ object.price_per_sq_ft }}</td>
            <td>$ {{ object.totalPrice }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
<br>

<div class="section-wrapper-small">
  <form id="confirm-delete-form" method="post">{% csrf_token %}
      <p>Are you sure you want to delete this item?</p>
      <input id="confirm-button" class="btn" type="submit" value="Confirm">
  </form>
  <button class="btn">
    <a  href="{% url 'orders:order-summary' object.proposal_id %}">Cancel</a>
  </button> <!-- HOME -->
</div>
{% endblock %}

mysite/orders/templates/orders/content.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %}New Order{% endblock %}

{% block content %}
<div class="section-wrapper form">
  {% if edit or form_name == 'line_item' %}
  <button class="btn rf">
    <a  href="{% url 'orders:order-summary' id %}">Go Back</a>
  </button>
  {% endif %}

  {% if form_name == 'customer' %}
    {% include 'orders/form_customer.html' %}
  {% elif form_name == 'proposal' %}
    {% include 'orders/form_proposal.html' %}
  {% elif form_name == 'line_item' %}
    {% include 'orders/form_line_item.html' %}
  {% else %}
    {% include 'orders/form_price.html' %}
  {% endif %}
</div>

{% if form_name != 'customer' and not edit %}
<div class="section-wrapper">
  <div class="inner-wrapper">
    <p>Order Summary</p>
    {% include 'orders/detail_line_item.html' %}
    <br>
    {% if form_name == 'line_item' %}
    <button class="btn rf">
      <a href="{% url 'orders:add-proposal' proposal_id %}">Next</a>
    </button>
    {% endif %}
  </div>
</div>
{% endif %}



{% endblock %}

mysite/orders/templates/orders/detail_line_item.html
<div class="line-item-table-wrapper">
  <table id="line-item-detail-table">
    <thead>
      <tr>
        <th colspan=2 class="line-item-table-buttons"></th>
        <th colspan=19></th>
        <th colspan=5>Height</th>
        <th colspan=2>Door Handle</th>
        <th>Resaque</th>
        <th colspan=2>Price</th>
      </tr>

      <tr>
        <th colspan=2 class="line-item-table-buttons"></th>
        <th>#</th>
        <th>Product</th>
        <th>Type</th>
        <th>Location</th>
        <th>Mount</th>
        <th>Frame</th>
        <th colspan=2>Trim</th>
        <th>Doors</th>
        <th># of Tposts</th>
        <th>Louver</th>
        <th>Tilt Rod</th>
        <th>Finish</th>
        <th>Stain</th>
        <th>Color</th>
        <th colspan=2>Hinges</th>
        <th>Width</th>
        <th>Height</th>
        <th>Center</th>
        <th>Left</th>
        <th>Right</th>
        <th>Middle</th>
        <th>Divider</th>
        <th>Height</th>
        <th>Cutout</th>
        <th>L frame</th>
        <th>Per Sq. Ft.</th>
        <th>Total</th>
      </tr>
    </thead>

    {% for item in lineitem %}
    <tbody>
      <tr>
        <td class="line-item-table-buttons">
          <a class="btn btn-yellow" href="{% url 'orders:edit-line-item' item.id %}" role="button">Edit</a>
        </td>
        <td class="line-item-table-buttons">
          <a class="btn btn-red" href="{% url 'orders:delete' item.id item.proposal_id %}" role="button">X</a>
        </td>
        <td>{{ forloop.counter }}</td>
        <td>{{ item.product }}</td>
        <td>{{ item.shutter_type }}</td>
        <td>{{ item.location }}</td>
        <td>{{ item.mount }}</td>
        <td>{{ item.frame_type|default_if_none:"" }}</td>
        <td>{{ item.trim|default_if_none:"" }}</td>
        <td>{{ item.trim_style|default_if_none:"" }}</td>
        <td>{{ item.panels }}</td>
        <td>{{ item.t_post|default_if_none:"" }}</td>
        <td>{{ item.get_louver_display }}</td>
        <td>{{ item.tilt_rod }}</td>
        <td>{{ item.finish }}</td>
        <td>{{ item.stain|default_if_none:"" }}</td>
        <td>{{ item.color }}</td>
        <td>{{ item.hinges }}</td>
        <td>{{ item.hinge_color }}</td>
        <td>{{ item.width }} {{ item.get_width_fraction_display }}</td>
        <td>{{ item.height|default_if_none:"" }} {{ item.get_height_fraction_display }}</td>
        <td>{{ item.height_center|default_if_none:"" }} {{ item.get_height_center_fraction_display }}</td>
        <td>{{ item.height_left|default_if_none:"" }} {{ item.get_height_left_fraction_display }}</td>
        <td>{{ item.height_right|default_if_none:"" }} {{ item.get_height_right_fraction_display }}</td>
        <td>{{ item.height_middle|default_if_none:"" }} {{ item.get_height_middle_fraction_display }}</td>
        <td>{{ item.height_divider|default_if_none:"" }} {{ item.get_height_divider_fraction_display }}</td>
        <td>{{ item.height_door_knob|default_if_none:"" }} {{ item.get_height_door_knob_fraction_display }}</td>
        <td>{{ item.door_handle_cutout|default_if_none:"" }}</td>
        <td>{{ item.resaque_lframe|yesno:"Yes," }}</td>
        <td>$ {{ item.price_per_sq_ft }}</td>
        <td>$ {{ item.totalPrice }}</td>
      </tr>
    </tbody>
    {% endfor %}
  </table>
</div>

mysite/orders/templates/orders/order_summary.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Order Summary{% endblock %}

{% block content %}
<div class="section-wrapper">
  <div class="inner-wrapper">
    <div class="row">
      <div class = "col-lg-12 col-md-12 col-sm-12 ra">
        <h2>Order Summary</h2>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-8 col-md-5 col-lg-4">
          <p class="summary-title">Customer</p>
          <a class="btn btn-yellow rf" href="{% url 'orders:edit-customer' customer.id %}" role="button">Edit</a> <!-- EDIT customer -->
          <hr/>
          {% include 'orders/detail_customer.html' %}
        </div>
        <div class="col-8 col-md-5 col-lg-4">
          <p class="summary-title">Order Details</p>
          <a class="btn btn-yellow rf" href="{% url 'orders:edit-proposal' proposal.id %}" role="button">Edit</a> <!-- EDIT agents, measured by -->
          <hr/>
          {% include 'orders/detail_proposal.html' %}
          <div class="report-section">
            <h6>Notes: </h6>
            {{ proposal.notes }}
          </div>
        </div>
        <div class="col-8 col-md-5 col-lg-4">
          <p class="summary-title">Price Details</p>
          <a class="btn btn-yellow rf" href="{% url 'orders:edit-price' proposal.id %}" role="button">Edit</a> <!-- EDIT price -->
          <hr/>
          {% include 'orders/detail_price.html' %}
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-12">
          <p class="summary-title">Order Items</p>
          <div class="rf">
            <button id="line-item-edit-button" class="btn btn-yellow">Edit</button> <!-- EDIT line items -->
            <a class="btn btn-green" href="{% url 'orders:add-line-item' proposal.id %}" role="button">Add</a> <!-- ADD line item -->
          </div>
          <hr/>
          {% include 'orders/detail_line_item.html' %}
        </div>
      </div>

      <br>

      <div class="row rf">
        <div class="col-12">
          <a class="btn" href="{% url 'reports:proposal-report' proposal.id %}" role="button">Proposal</a> <!-- CREATE proposal -->

          <a class="btn" href="{% url 'reports:manufacturing-report' proposal.id %}" role="button">Manufacturing Report</a> <!-- CREATE manufacturing report -->

          <a class="btn" href="{% url 'reports:invoice-report' proposal.id %}" role="button">Invoice</a> <!-- CREATE invoice -->

          <a class="btn" href="{% url 'dashboard:home' %}" role="button">Exit</a> <!-- HOME -->
        </div>
      </div>

    </div>
  </div>
</div>

{% endblock %}