mysite/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.Login, name='login-page'),
    path('home', views.Home, name='home'),
    path('dashboard/<status>', views.updateList, name='update-list'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('orders/', include('orders.urls')),
    path('reports/', include('reports.urls')),
]

mysite/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('add_customer', views.addCustomer, name='add-customer'),
    path('add_proposal/<int:pk>', views.addProposal, name='add-proposal'),
    path('add_line_item/<int:pk>', views.addLineItem, name='add-line-item'),
    path('edit-customer/<int:pk>', views.editCustomer, name='edit-customer'),
    path('edit-proposal/<int:pk>', views.editProposal, name='edit-proposal'),
    path('edit-line-item/<int:pk>', views.editLineItem, name='edit-line-item'),
    path('edit-price/<int:pk>', views.editPrice, name='edit-price'),
    path('order-summary/<int:pk>', views.orderSummary, name='order-summary'),
    path('delete/<int:pk>/<int:pk2>', views.lineItemDelete.as_view(), name='delete'),
    path('delete-proposal/<int:pk>/<status>', views.confirm_status, name='confirm-status'),
    path('update_status/<int:pk>/<status>', views.update_status, name='update-status'),
]

mysite/templates/base.html
{% load static %}<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static 'css/bootstrap.min.css' %}{% endblock %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    {% block responsive %}<meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">{% endblock %}
    {% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE"/>{% endblock %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
  </head>

  <body>
    <div id="page">
      <div id="header">
      {% block header %}
      {% include "header.html" %}
      {% endblock %}

      {% block navbar %}
      {% include "navbar.html" %}
      {% endblock %}
      </div>

      {% block sidebar %}
      {{ sidebar_content }}
      {% endblock %} <!-- END sidebar -->

      <div id="content">
        <div class="content-wrapper">
          {% block content %}
          {{ content }}
          {% endblock %}
        </div>
      </div> <!-- END content -->

      {% block footer %}
      <footer id="footer">
        <div class="footer-wrapper ra">
        Shutterize. ®
        </div>
      </footer> <!-- END footer -->
      {% endblock %}

    </div> <!-- END page -->

    <!--common JS -->
    <script type="text/javascript" src="{% static 'js/jquery-3.3.1.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/common-scripts.js' %}"></script>
  </body>
</html>

mysite/templates/header.html
{% load static %}
<header class="noprint">
  <div class="container">
    <div class="header-wrapper clearfix">
      <div id="header-logo">
        <img src="{% static 'img/shutterize_logo.png' %}" alt="Shutterize Software">
      </div>

      <div id="header-text">
        <h4 id="header-title">
          <a href="{% url 'dashboard:home' %}" title="Shutterize" rel="home">Shutterize</a>
        </h4>
      </div>

      <div id="logout-button">
        <a class="btn btn-radius btn-main" href="{% url 'dashboard:login-page' %}" role="button">Logout</a>
      </div>

    </div>
  </div>
</header>

mysite/templates/letterhead.html
{% load static %}

<div class="row mt">
  <div class = "col-lg-8 col-md-8 col-sm-12">
    <div id="company-logo">
      <img src="{% static 'img/jmblinds_logo.png' %}" alt="JM Curtain Designer and Blinds L.L.C">
    </div>
  </div>

  <div class = "col-lg-4 col-md-4 col-sm-12">
    <p class="ra">
      901 Perkins Ave. Ste. A.<br>
      Mission, TX 78572<br>
      (956) 583-9531<br>
      www.jmblindsrgv.com<br>
      <b>Toll Free:</b> (1) 877-271-9894
    </p>
  </div>
</div> <!-- END company letterhead -->

mysite/templates/navbar.html
<div class="main-menu noprint">
  <div class="container">
    <div class="menu-wrapper">

      <div id="create-button" class="inline">
        <a class="btn btn-radius btn-main" href="{% url 'orders:add-customer' %}" role="button">New Proposal</a>
      </div>

      <div class="rf">
        <a class="icon-btn" href="{% url 'dashboard:home' %}" role="button">
          <i class="fas fa-home"></i>
        </a>

        <a class="icon-btn" href="{% url 'dashboard:update-list' 'Deleted' %}" role="button">
          <i class="far fa-trash-alt"></i>
        </a>
      </div>

    </div>
  </div>
</div>