mysite/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.Login, name='login-page'),
    path('home', views.Home, name='home'),
    path('dashboard/<status>', views.updateList, name='update-list'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('orders/', include('orders.urls')),
    path('reports/', include('reports.urls')),
]

mysite/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('add_customer', views.addCustomer, name='add-customer'),
    path('add_proposal/<int:pk>', views.addProposal, name='add-proposal'),
    path('add_line_item/<int:pk>', views.addLineItem, name='add-line-item'),
    path('edit-customer/<int:pk>', views.editCustomer, name='edit-customer'),
    path('edit-proposal/<int:pk>', views.editProposal, name='edit-proposal'),
    path('edit-line-item/<int:pk>', views.editLineItem, name='edit-line-item'),
    path('edit-price/<int:pk>', views.editPrice, name='edit-price'),
    path('order-summary/<int:pk>', views.orderSummary, name='order-summary'),
    path('delete/<int:pk>/<int:pk2>', views.lineItemDelete.as_view(), name='delete'),
    path('delete-proposal/<int:pk>/<status>', views.confirm_status, name='confirm-status'),
    path('update_status/<int:pk>/<status>', views.update_status, name='update-status'),
]

mysite/dashboard/views.py
from django.urls import reverse
from django.shortcuts import render, redirect
from orders.models import proposal
import json


def Login(request):
    return redirect(reverse('login'))


def Home(request):
    p = proposal.objects.filter(status="Pending")

    return render(request, 'dashboard/home.html', {'proposals': p, 'status': 'Pending'})


def updateList(request, status):
    p = proposal.objects.filter(status=status)

    return render(request, 'dashboard/home.html', {'proposals': p, 'status': status})

mysite/dashboard/templates/dashboard/home.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Home{% endblock %}

{% block logolink %}{% url 'dashboard:home' %}{% endblock %}

{% block content %}
<div class="inner-wrapper">
  <div class="row">
    <div class="col-md-2">
      {% include "dashboard/side_menu.html" %}
    </div>

    <div class="col-md-6 offset-md-2">
      {% include "dashboard/list_index.html" %}
    </div>
  </div>
</div>
{% endblock %} <!-- END content -->

mysite/dashboard/templates/dashboard/letterhead.html
{% load static %}

<div class="row mt">
  <div class = "col-lg-8 col-md-8 col-sm-12">
    <div id="company-logo">
      <img src="{% static 'img/jmblinds_logo.png' %}" alt="JM Curtain Designer and Blinds L.L.C">
    </div>
  </div>

  <div class = "col-lg-4 col-md-4 col-sm-12">
    <p class="ra">
      901 Perkins Ave. Ste. A.<br>
      Mission, TX 78572<br>
      (956) 583-9531<br>
      www.jmblindsrgv.com<br>
      <b>Toll Free:</b> (1) 877-271-9894
    </p>
  </div>
</div> <!-- END proposal header -->

mysite/dashboard/templates/dashboard/list_index.html
{% load widget_tweaks %}
{% load humanize %}

{% if status != "Deleted" %}
<div class="row">
  <div class="col">
    <div class="list-menu">
      <ul class="nav">
        {% if status == "Pending" %}
        <li class="nav-item">
          <a id="active-filter" class="nav-link active" href="{% url 'dashboard:update-list' 'Pending' %}">Active</a>
        </li>
        <li class="nav-item">
          <a id="completed-filter" class="nav-link" href="{% url 'dashboard:update-list' 'Completed' %}">Completed</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a id="active-filter" class="nav-link" href="{% url 'dashboard:update-list' 'Pending' %}">Active</a>
        </li>
        <li class="nav-item">
          <a id="completed-filter" class="nav-link active" href="{% url 'dashboard:update-list' 'Completed' %}">Completed</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</div>
{% else %}
<div class="list-title">Deleted Orders</div>
{% endif %}

{% for p in proposals %}
  <div class="row">
    <div class="col">
      <div class="list-section clearfix" value="{{ p.status }}">
        <div class="lf"><h6 class="no-margin list-item-title">{{ p.customer }} - ${{ p.order_total|floatformat|intcomma }}</h6></div>

        <div class="rf">
          {% if status == "Pending" %}
          <a class="btn btn-complete" href="{% url 'orders:confirm-status' p.id 'Completed' %}" role="button">&#x2714;</a>
          {% endif %}

          {% if status != "Deleted" %}
          <a class="btn btn-delete" href="{% url 'orders:confirm-status' p.id 'Deleted' %}" role="button">&#x2718;</a>
          {% endif %}

        </div>
        <br>

        <br>
        <div class="month-field" value="{{ p.created_date.month }}"><b>Created date:</b> {{ p.created_date }}</div>
        <div><b>Installation date:</b> {{ p.installation_date }}</div>
        <br>

        <div class="row rf">
          <div class="col">
            <a class="btn" href="{% url 'orders:order-summary' p.id %}" role="button">View</a>

            {% if status == "Deleted" %}
              <a class="btn" href="{% url 'orders:confirm-status' p.id 'Pending' %}" role="button">Restore</a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endfor %}

mysite/dashboard/templates/dashboard/side_menu.html
Filter by:<br><br>

Month
<form>
  <select id="monthFilter" class="custom-select" name="months">
    <option value=0>All</option>
    <option value=1>January</option>
    <option value=2>February</option>
    <option value=3>March</option>
    <option value=4>April</option>
    <option value=5>May</option>
    <option value=6>June</option>
    <option value=7>July</option>
    <option value=8>August</option>
    <option value=9>September</option>
    <option value=10>October</option>
    <option value=11>November</option>
    <option value=12>December</option>
  </select>
  <br><br>
</form>

mysite/dashboard/templates/dashboard/template_header.html
<div class="row mt">
  <div class = "col-lg-8 col-md-8 col-sm-12">
    <h2>LOGO</h2>
    <p><b>Serving the Rio Grande Valley</b></p>
  </div>

  <div class = "col-lg-4 col-md-4 col-sm-12 right-align">
    <p>901 Perkins Ave. Ste. A.</p>
    <p>Mission, TX 78572</p>
    <p><b>P:</b> (956) 583-9531</p>
    <p><b>E:</b> www.jmblindsrgv.com</p>
    <p><b>Toll Free:</b> 1-877-271-9894</p>
  </div>
</div> <!-- END proposal header -->